"""tiny_skill_agent の公開 API。"""

from __future__ import annotations

from .agent import SkillAgent, SkillSessionState
from .action import (
    ACTION_NAMES,
    ActionCatalog,
    ActionOperations,
    ActionPayload,
    WORKSPACE_ACTION_NAMES,
    create_file,
    extract_action_args,
    extract_action_bool_field,
    extract_action_directory_path,
    extract_action_file_path,
    extract_action_int_field,
    extract_action_scope,
    extract_action_text_alias,
    extract_action_text_field,
    insert_edit_into_file,
    read_file_for_action,
    replace_string_in_file,
    run_skill_script,
)
from .cli import cli, main
from .prompt import (
    SYSTEM_ACTOR_PROMPT,
    SYSTEM_FINALIZER_PROMPT,
    SYSTEM_SELECTOR_PROMPT,
)
from .skills import (
    Skill,
    SkillDiagnostic,
    SkillRegistry,
    SkillValidationReport,
    build_selection_input,
    build_skill_adherence_block,
    build_task_context_input,
    build_validation_payload,
    ensure_skill_allows_action,
    ensure_skill_allows_workspace_path,
    find_explicit_skill_mentions,
    list_allowed_actions_for_skill,
    load_skill,
    normalize_selected_skill_names,
    parse_skill_frontmatter,
    resolve_action_skill,
    resolve_skill_md_path,
    skill_allows_workspace_path,
    summarize_blocking_skill_errors,
    validate_skill_roots,
)
from .skill_files import (
    classify_skill_file,
    find_skill_files,
    is_script_path,
    normalize_skill_path,
    read_text_resource,
    read_skill_resource,
    resolve_skill_file_request,
)
from .utils import (
    append_jsonl_log,
    current_timestamp_iso,
    extract_response_text,
    flatten_text_content,
    parse_json_from_text,
    serialize_openai_response,
    strip_thinking,
    truncate_text,
)
from .workspace import (
    build_ambiguous_path_error,
    build_read_file_payload,
    build_search_result,
    edit_workspace_file,
    find_workspace_files,
    infer_run_script_path,
    is_relative_to,
    iter_searchable_files,
    list_workspace_directory,
    looks_like_python_invocation,
    normalize_hint_path,
    normalize_script_request,
    normalize_search_limit,
    normalize_workspace_path,
    read_existing_workspace_text,
    read_utf8_text_file,
    read_workspace_file,
    resolve_workspace_file_request,
    score_path_match,
    should_skip,
    slice_text_by_lines,
    workspace_file_result,
    write_utf8_text_file,
    write_workspace_file,
)
